spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque
spring.datasource.username=biblio_user
spring.datasource.password=biblio123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration des logs
logging.level.com.bibliotheque=DEBUG
logging.file.name=logs/api-bibliotheque.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n